    spring.application.name=Clase Springboot
    server.port=${PORT:8081}
    # ACTIVAR PERFIL LOCAL
    # spring.profiles.active=local

    spring.datasource.url=${DATABASE_URL}
    spring.datasource.username=${DATABASE_USERNAME}
    spring.datasource.password=${DATABASE_PASSWORD}

    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.default_batch_fetch_size=20

    spring.sql.init.mode=never

    # CLOUDINARY
    CLOUDINARY_URL=cloudinary://831124813753864:z8aacKfwpPY2JYvM_PJfTSCvsAI@dzkfjusut
    CLOUDINARY_API_KEY=831124813753864
    CLOUDINARY_API_SECRET=z8aacKfwpPY2JYvM_PJfTSCvsAI

    # Seguridad y Archivos
    spring.servlet.multipart.max-file-size=10MB
    spring.servlet.multipart.max-request-size=10MB
    admin.user=turco_admin
    admin.pass=1234