# Datos de TU Postgres local
spring.datasource.url=jdbc:postgresql://localhost:5432/elturco_db
spring.datasource.username=postgres
spring.datasource.password=germanpostgres.10

# Dialecto para tu versión de Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Forzar que en local siempre intente actualizar tablas
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true


# SQL Inicial local
spring.sql.init.mode=never